/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.etl.views;

/**
 *
 * @author Nadeesha
 */
import com.sun.management.jmx.Trace;
import com.etl.controllers.ctrl_clencedData;

public class view_panelCleansedData extends javax.swing.JPanel {

    /**
     * Creates new form view_panelCleansedData
     */
      boolean  rmvInvalidEntry,roundNumbers,rmvDublicates,removeNull,sortData;
    String fileName;
    public view_panelCleansedData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        chk_rmvInvalidEntrys = new javax.swing.JCheckBox();
        chk_rmvDublicatedValues = new javax.swing.JCheckBox();
        chk_rmvNullValues = new javax.swing.JCheckBox();
        chk_roundNumbers = new javax.swing.JCheckBox();
        chk_sortDataSet = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(73, 162, 176));
        jPanel1.setMaximumSize(new java.awt.Dimension(679, 430));
        jPanel1.setMinimumSize(new java.awt.Dimension(679, 430));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Attribute Mapper");

        chk_rmvInvalidEntrys.setText("Remove invalid entryes ");

        chk_rmvDublicatedValues.setText("Remove dublicated values");

        chk_rmvNullValues.setText("Remove Null Values");

        chk_roundNumbers.setText("Round nummbers");

        chk_sortDataSet.setText("sort data set");
        chk_sortDataSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_sortDataSetActionPerformed(evt);
            }
        });

        jCheckBox6.setText("jCheckBox1");

        jCheckBox7.setText("jCheckBox1");

        jCheckBox8.setText("jCheckBox1");

        jCheckBox9.setText("jCheckBox1");

        jCheckBox10.setText("jCheckBox5");

        jButton3.setText("CANCEL");

        btn_next.setText("NEXT");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chk_rmvDublicatedValues)
                            .addComponent(chk_rmvInvalidEntrys)
                            .addComponent(chk_roundNumbers)
                            .addComponent(chk_rmvNullValues)
                            .addComponent(chk_sortDataSet))
                        .addGap(184, 184, 184)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox9)
                            .addComponent(jCheckBox10))))
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel5)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chk_rmvInvalidEntrys)
                        .addGap(18, 18, 18)
                        .addComponent(chk_roundNumbers)
                        .addGap(18, 18, 18)
                        .addComponent(chk_rmvDublicatedValues)
                        .addGap(18, 18, 18)
                        .addComponent(chk_rmvNullValues)
                        .addGap(18, 18, 18)
                        .addComponent(chk_sortDataSet))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox6)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox7)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox8)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox9)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chk_sortDataSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_sortDataSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_sortDataSetActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed

        try{

            if(chk_sortDataSet.isSelected()){

                sortData=true;

            }
            if(chk_rmvDublicatedValues.isSelected()){

                rmvDublicates=true;

            }
            if(chk_rmvInvalidEntrys.isSelected()){

                rmvInvalidEntry=true;

            }
            if(chk_roundNumbers.isSelected()){

                roundNumbers=true;

            }if(chk_rmvNullValues.isSelected()){

                removeNull=true;

            }

            ctrl_clencedData clencedData = new ctrl_clencedData();
            clencedData.clenced(rmvInvalidEntry, roundNumbers, rmvDublicates, removeNull, sortData,fileName);

        }catch(Exception er){
            System.out.println("error in view_clenced data "+er);

        }
    }//GEN-LAST:event_btn_nextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_next;
    private javax.swing.JCheckBox chk_rmvDublicatedValues;
    private javax.swing.JCheckBox chk_rmvInvalidEntrys;
    private javax.swing.JCheckBox chk_rmvNullValues;
    private javax.swing.JCheckBox chk_roundNumbers;
    private javax.swing.JCheckBox chk_sortDataSet;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
